---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: 遷移儲存資料時，使用 REST API 手動加入儲存後端。遷移 VASA Provider 資料時，資料會從現有的 Derby 資料庫匯出並匯入 MongoDB 資料庫。 
---
= 遷移 VASA 提供者並更新 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
依照本節中的步驟，將 VASA 提供者從ONTAP tools for VMware vSphere移轉到ONTAP tools for VMware vSphere，並更新 VMware Live Site Recovery 裝置上的儲存複製適配器 (SRA)。



== 遷移 VASA 提供者的步驟

. 若要在現有的適用ONTAP tools for VMware vSphere上啟用 Derby PORT 1527，請啟用 root 使用者並透過 SSH 登入 CLI。然後，執行以下命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphere的 OVA。
. 新增要移轉到ONTAP tools for VMware vSphere的 vCenter Server 執行個體。請參閱link:../configure/add-vcenter.html["新增 vCenter Server 執行個體"]了解更多。
. 透過 vCenter Server API 將儲存後端本機整合到ONTAP工具插件中。請參閱link:../configure/add-storage-backend.html["使用 vSphere 用戶端介面新增儲存後端"]了解更多。
. 取得存取權杖以驗證 REST API 請求。請使用以下範例，並將變數替換為特定於您環境的值。
+
+



[listing]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
複製並保存回應中傳回的存取令牌。。從 Swagger 或 Postman 發出以下 API 進行遷移。

+

[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
您可以透過以下網址存取 Swagger： `\https://$FQDN_IP_PORT/` ， 例如： `\https://10.67.25.33:8443/` 。

+

[]
====
HTTP 方法和端點

此 REST API 呼叫使用下列方法和端點。

|===


| HTTP 方法 | *小路* 


| 郵政 | /api/v1 
|===
*加工類型*

非同步

*Curl 範例*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
其他版本遷移的請求主體：

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
JSON 輸出範例

系統傳回一個作業對象。儲存作業標識符以便在下一個步驟中使用。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. 在 Swagger 中使用以下 URI 檢查狀態：
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<migration_id>?includeSubJobsAndTasks=true`
----
+
作業完成後，請查看作業回應中的遷移報告。

. 將ONTAP tools for VMware vSphere新增至 vCenter Server。
. 使用ONTAP tools for VMware vSphere 的VASA 提供者。有關說明，請參閱link:../configure/registration-process.html["註冊 VASA 提供程序"]。
. 註冊後，請在 vSphere Client 的「儲存提供者」下驗證 VASA 提供者的名稱及其狀態。VASA 提供者應在線上顯示，確認註冊成功。
. link:../manage/enable-services.html["啟用 VASA 提供程序"]ONTAP tools for VMware vSphere上的服務。
. 請依照下列步驟停止ONTAP tools for VMware vSphere：
+
.. 在ONTAP工具 9.x 中，開啟 Web 控制台。
.. 存取維護控制台。
.. 進入 `1`選擇“應用程式配置”選單。
.. 進入 `5`停止 VASA Provider 和 SRA 服務。
.. 在 vSphere Client 中，導覽至「清單」>「儲存提供者」。
.. 從儲存後端選擇ONTAP工具 9.x VASA 提供程序，然後按一下「刪除」。
+
舊 VASA 提供者停止後，vCenter Server 將故障轉移到ONTAP tools for VMware vSphere。所有資料儲存庫和虛擬機器均可訪問，並由適用於ONTAP tools for VMware vSphere提供服務。



. 遷移後的 NFS 和 VMFS 資料儲存會在資料儲存發現作業完成後出現在ONTAP tools for VMware vSphere中，該作業可能需要長達 30 分鐘。在概覽頁面上檢查它們的可見性。
. 使用 Swagger 或 Postman 中的以下 API 執行補丁遷移：
+
[]
====
HTTP 方法和端點

此 REST API 呼叫使用下列方法和端點。

|===


| HTTP 方法 | *小路* 


| 修補 | /api/v1 
|===
*加工類型*

非同步

請在 Swagger 中使用以下 URI：

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Curl 範例*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
JSON 輸出範例

傳回一個作業對象。您應該保存作業標識符以便在下一步中使用它。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+
修補操作請求體為空。




NOTE: UUID 是回應遷移後 API 回傳的遷移 UUID。

執行補丁遷移API後，所有虛擬機器都符合儲存策略。

.下一步
完成遷移並將ONTAP Tools 10.4 註冊到 vCenter Server 後，請依照下列步驟操作：

* 等待*發現*完成，系統會自動在所有主機上刷新憑證。
* 等待資料儲存區和虛擬機器操作開始。等待時間取決於主機、資料儲存和虛擬機器的數量。如果您不等待，您可能會偶爾看到失敗。


升級後，如果虛擬機器的合規性狀態已過時，請使用以下步驟重新套用儲存策略：

. 前往資料儲存並選擇*摘要*>*虛擬機器儲存策略*。
+
系統顯示*虛擬機器儲存策略合規性*下的合規性狀態為*過時*。

. 選擇儲存虛擬機器策略和對應的虛擬機器。
. 選擇*應用*。
+
*虛擬機器儲存策略合規性*下的合規性狀態顯示為合規性。相關資訊

+
** link:../concepts/rbac-learn-about.html["了解適用於ONTAP tools for VMware vSphere"]
** link:../upgrade/upgrade-ontap-tools.html["將適用於ONTAP tools for VMware vSphere升級至 10.4"]






== 更新儲存複製適配器（SRA）的步驟

.開始之前
在復原計畫中，受保護站點是指虛擬機器目前運作的位置，而復原站點是指虛擬機器將被復原的位置。 SRM介面顯示復原計畫的狀態，其中包含受保護網站和復原網站的詳細資訊。在復原計畫中，「*CleanupP*」和「*Reprotect*」按鈕處於停用狀態，而「TEST」和「RUN」按鈕則保持啟用狀態。這表示該站點已準備好進行資料恢復。在遷移 SRA 之前，請先驗證一個網站處於受保護狀態，另一個網站處於復原狀態。


NOTE: 若故障轉移已完成但重新保護仍處於待定狀態，請勿開始移轉。確保在繼續遷移之前重新保護過程已完成。如果正在進行測試故障轉移，請清理測試故障轉移並開始遷移。

. 請依照下列步驟刪除 VMware Site Recovery 中適用於 VMware vSphere 9.xx 的ONTAP工具 SRA 適配器：
+
.. 前往 VMware Live Site Recovery 設定管理頁面
.. 前往*儲存複製適配器*部分。
.. 從省略號選單中選擇*重設配置*。
.. 從省略號選單中選擇*刪除*。


. 在保護站點和復原站點上執行這些步驟。
+
.. link:../manage/enable-services.html["ONTAP tools for VMware vSphere"]
.. 使用下列步驟ONTAP tools for VMware vSpherelink:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 設備上設定 SRA"]。
.. 在 VMware Live Site Recovery 使用者介面頁面，執行 *發現陣列* 和 *發現裝置* 操作，確認裝置顯示與遷移前一致。



