---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 您應該建立保護群組來保護受保護網站上的一組虛擬機器。 
---
= 配置受保護站點和復原站點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該建立保護群組來保護受保護網站上的一組虛擬機器。

當您新增的資料儲存區時，您可以將其新增至現有的資料儲存區群組中，也可以新增新的資料儲存區並建立新的磁碟區或一致性群組以進行保護。將新的資料儲存區新增至受保護的一致性群組或磁碟區後，更新SnapMirror並在受保護網站和復原網站上執行儲存發現。您可以手動或按計劃執行發現，以確保偵測到並保護新的資料儲存區。



== 將受保護站點和復原站點配對

您應該將使用 vSphere Client 建立的受保護網站和復原網站配對，以啟用儲存複製適配器 (SRA) 來發現儲存系統。


NOTE: 儲存複製適配器 (SRA) 支援具有自動故障轉移雙工類型的一個同步關係的扇出以及一致性組上的非同步關係SnapMirror 。但是，不支援在一致性群組上使用兩個非同步SnapMirror進行扇出或在磁碟區上使用扇出 SnapMirror 進行扇出。

.開始之前
* 您應該在受保護網站和復原站點上安裝 VMware Live Site Recovery。
* 您應該在受保護網站和復原網站上安裝 SRA。


.步驟
. 在 vSphere Client 主頁上雙擊 *Site Recovery*，然後選擇 *Sites*。
. 選擇*物件* > *操作* > *配對網站*。
. 在*配對網站復原管理員伺服器*對話方塊中，輸入受保護網站的 Platform Services Controller 的位址，然後選擇*下一步*。
. 在「選擇 vCenter Server」部分中，執行下列操作：
+
.. 驗證受保護網站的 vCenter Server 是否顯示為符合的候選配對。
.. 輸入 SSO 管理憑證，然後選擇 *完成*。


. 如果出現提示，請選擇「是」接受安全性憑證。


.結果
受保護網站和復原網站都會出現在「物件」對話方塊中。



== 配置保護組

.開始之前
您應確保來源網站和目標網站均已配置以下內容：

* 安裝了相同版本的 VMware Live Site Recovery
* 虛擬機
* 配對的受保護站點和復原站點
* 來源資料儲存區和目標資料儲存區應安裝在各自的站點上


.步驟
. 登入 vCenter Server 並選擇“Site Recovery”>“Protection Groups”。
. 在「保護群組」窗格中，選擇「新建」。
. 指定保護群組的名稱和描述、方向，然後選擇*下一步*。
. 在「類型」欄位中，選擇「資料儲存組（基於陣列的複製）」作為 NFS 和 VMFS 資料儲存區的「類型」欄位選項...*。故障域僅包含已啟用複製的 SVM。系統會顯示僅實施了對等連線且沒有問題的 SVM。
. 在「複製群組」標籤中，選擇已啟用的陣列對或具有您配置的虛擬機器的複製群組，然後選擇「*下一步*」。
+
複製組上的所有虛擬機器均新增至保護組。

. 您可以選擇現有的復原計劃，也可以透過選擇「新增至新復原計劃」來建立新的復原計劃。
. 在「即將完成」標籤中，查看您建立的保護群組的詳細信息，然後選擇「完成」。

