---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: 雖然 REST 建立了一套通用的技術和最佳實踐，但每個 API 的具體實作可能會根據設計選擇而有所不同。在使用之前，您應該熟悉ONTAP tools for VMware vSphere的設計方式。 
---
= 適用於ONTAP tools for VMware vSphere的實作詳細信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
雖然 REST 建立了一套通用的技術和最佳實踐，但每個 API 的具體實作可能會根據設計選擇而有所不同。在使用之前，您應該熟悉ONTAP tools for VMware vSphere的設計方式。

REST API 包含多個資源類別，例如 vCenter 和 Aggregates。回顧link:../automation/api-reference.html["API 參考"]了解更多。



== 如何存取 REST API

您可以透過ONTAP工具 IP 位址和連接埠存取適用ONTAP tools for VMware vSphere。完整的 URL 包含幾個部分，包括：

* ONTAP工具 IP 位址和連接埠
* API 版本
* 資源類別
* 特定資源


您必須在初始設定期間設定 IP 位址，而連接埠固定為 8443。 URL的第一部分對於每個ONTAP tools for VMware vSphere都是一致的；只有資源類別和特定資源在端點之間會變更。


CAUTION: 以下範例中的 IP 位址和連接埠值僅用於說明目的。您需要根據您的環境變更這些值。

.存取身份驗證服務的範例
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

此 URL 可用於透過 POST 方法請求存取權杖。

.列出 vCenter 伺服器的範例
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

此 URL 可用於透過 GET 方法請求已定義的 vCenter 伺服器執行個體清單。



== HTTP 詳細資訊

ONTAP tools for VMware vSphere使用 HTTP 和相關參數對資源實例和集合進行操作。  HTTP 實作的詳細資訊如下所示。



=== HTTP 方法

REST API 支援的 HTTP 方法或動詞如下表所示。

[cols="15,15,70"]
|===
| 方法 | 增刪改查 | 描述 


| 得到 | 讀 | 檢索資源實例或集合的物件屬性。當與集合一起使用時，這被視為列表操作。 


| 郵政 | 創造 | 根據輸入參數建立一個新的資源實例。 


| 放 | 更新 | 使用提供的 JSON 請求正文更新整個資源實例。使用者不可修改的鍵值將會保留。 


| 修補 | 更新 | 請求將請求中的一組選定的變更套用到資源實例。 


| 刪除 | 刪除 | 刪除現有的資源實例。 
|===


=== 請求和回應標頭

下表總結了 REST API 使用的最重要的 HTTP 標頭。

[cols="30,15,55"]
|===
| 標題 | 類型 | 用法說明 


| 接受 | 要求 | 這是客戶端應用程式可以接受的內容類型。有效值包括“\*/*”或 `application/json`。 


| x-授權 | 要求 | 包含用於識別透過客戶端應用程式發出請求的使用者的存取權杖。 


| 內容類型 | 回覆 | 由伺服器傳回 `Accept`請求標頭。 
|===


=== HTTP 狀態碼

REST API 使用的 HTTP 狀態碼如下所述。

[cols="15,20,65"]
|===
| 程式碼 | 意義 | 描述 


| 200 | 好的 | 表示呼叫成功但未建立新的資源實例。 


| 201 | 創建 | 已成功建立具有資源實例唯一識別碼的物件。 


| 202 | 公認 | 請求已被接受，並且已建立後台作業來執行該請求。 


| 204 | 沒有內容 | 儘管沒有返回任何內容，但請求成功。 


| 400 | 錯誤的請求 | 請求輸入無法識別或不合適。 


| 401 | 未經授權 | 使用者未獲得授權，必須進行身份驗證。 


| 403 | 禁止 | 由於授權錯誤，存取被拒絕。 


| 404 | 未找到 | 請求中引用的資源不存在。 


| 409 | 衝突 | 嘗試建立物件失敗，因為該物件已存在。 


| 500 | 內部錯誤 | 伺服器發生一般內部錯誤。 
|===


== 驗證

使用存取令牌對 REST API 進行客戶端身份驗證。令牌和身份驗證過程的相關特徵包括：

* 客戶端必須使用ONTAP工具管理器管理員憑證（使用者名稱和密碼）請求令牌。
* 令牌的格式為 JSON Web 令牌 (JWT)。
* 每個令牌在 60 分鐘後過期。
* 來自客戶端的 API 請求必須包含令牌 `x-auth`請求標頭。


參考link:../automation/first-call.html["您的第一個 REST API 呼叫"]有關請求和使用存取令牌的範例。



== 同步和非同步請求

大多數 REST API 呼叫都快速完成，因此同步運行。也就是說，它們在請求完成後會傳回狀態代碼（例如 200）。需要更長時間才能完成的請求使用後台作業非同步運行。

發出非同步運行的 API 呼叫後，伺服器傳回 202 HTTP 狀態碼。這表明請求已被接受但尚未完成。您可以查詢後台作業以確定其狀態，包括成功或失敗。

非同步處理用於幾種類型的長時間運行的操作，包括資料儲存和 vVol 操作。有關更多信息，請參閱 Swagger 頁面 REST API 的作業管理器類別。
