---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 儲存後端是 ESXi 主機用於資料儲存的系統。 
---
= 新增儲存後端
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增儲存後端可讓您加入ONTAP叢集。

*關於此任務*

如果在多租用戶設定中，vCenter 會充當具有關聯 SVM 的租用戶，則使用ONTAP工具管理器新增叢集。將儲存後端與 vCenter Server 關聯，以將其全域對應到已加入的 vCenter Server 執行個體。 vCenter 租用戶必須加入所需的儲存虛擬機器 (SVM)。這使得 SVM 用戶能夠配置vVols資料儲存。您可以使用 SVM 在 vCenter 中新增儲存。

使用ONTAP工具使用者介面新增具有叢集或 SVM 憑證的本機儲存後端。這些儲存後端僅限於單一 vCenter。在本機使用叢集憑證時，關聯的 SVM 會自動對應到 vCenter 來管理vVols或 VMFS。對於 VMFS 管理（包括 SRA）， ONTAP工具支援 SVM 憑證，而無需全域叢集。

[role="tabbed-block"]
====
.使用ONTAP工具管理器
--

NOTE: 在多租用戶設定中，您可以全域新增儲存後端集群，並在本機上新增 SVM 以使用 SVM 使用者憑證。

.步驟
. 從 Web 瀏覽器啟動ONTAP工具管理器： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的適用於ONTAP tools for VMware vSphere管理員憑證登入。
. 從側邊欄中選擇*儲存後端*。
. 新增儲存後端並提供伺服器 IP 位址或 FQDN、使用者名稱和密碼詳細資訊。
+

NOTE: 支援 IPv4 和 IPv6 位址管理 LIF。



--
.使用 vSphere 用戶端使用者介面
--

NOTE: 透過 vSphere 用戶端使用者介面配置儲存後端時，需要注意的是， vVols資料儲存不支援直接新增 SVM 使用者。

. 登入 vSphere 客戶端。
. 在捷徑頁面中，選擇插件部分下的* NetApp ONTAP工具*。
. 從側邊欄中選擇*儲存後端*。
. 新增儲存後端並提供伺服器 IP 位址、使用者名稱、密碼和連接埠詳細資訊。
+

NOTE: 若要直接新增 SVM 用戶，您可以新增基於叢集的憑證以及 IPv4 和 IPv6 位址管理 LIF，或使用 SVM 管理 LIF 提供基於 SVM 的憑證。



.下一步是什麼？
清單刷新，您可以在清單中看到新新增的儲存後端。

--
====