---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 您可以編輯受保護主機叢集的SnapMirror關係。您可以新增、修改和刪除關係。但是，您不能編輯一致性群組名稱。 
---
= 修改受保護的主機集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行下列任務作為修改保護的一部分。您可以在相同工作流程中執行所有變更。

* 在受保護的叢集中新增新的資料儲存或主機。
* 將新的SnapMirror關係加入到保護設定中。
* 從保護設定中刪除現有的SnapMirror關係。
* 修改現有的SnapMirror關係。




== 監控主機叢集保護

使用此程序來監控主機群集保護的狀態。您可以監控每個受保護的主機叢集及其保護狀態、 SnapMirror關係、資料儲存和對應的SnapMirror狀態。

.步驟
. 登入 vSphere 客戶端。
. 導覽至 * NetApp ONTAP工具* > *保護* > *主機叢集關係*。
+
保護列下方的圖示顯示保護狀態

. 將滑鼠懸停在圖示上可以查看更多詳細資訊。




== 新增新的資料儲存或主機

使用此程序來保護新新增的資料儲存區或主機。您可以使用 vCenter 本機使用者介面將新主機新增至受保護的叢集或在主機叢集上建立新的資料儲存區。

.步驟
. 登入 vSphere 客戶端。
. 若要編輯受保護叢集的屬性，您可以
+
.. 導覽至 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 如果您已在 vCenter 本機使用者介面中建立了資料儲存區，則該資料儲存區將顯示為不受保護。使用者介面在對話方塊中顯示叢集中的所有資料儲存及其保護狀態。選擇*保護*按鈕以啟用完全保護。
. 如果您新增了新的 ESXi 主機，則保護狀態顯示為部分受保護。選擇SnapMirror設定下的省略號選單，然後選擇 *編輯* 設定新新增的 ESXi 主機的接近度。
+

NOTE: 對於非同步類型關係，由於您無法將第三層站點的目標 SVM 新增至同一個ONTAP工具實例，因此不支援編輯操作。但是，您可以使用目標 SVM 的系統管理員或 CLI 來變更關係配置。

. 進行必要的更改後，選擇“*儲存*”。
. 您可以在「保護集群」視窗中看到變更。


vCenter 任務已創建，您可以在「最近任務」面板中追蹤進度。



== 新增新的SnapMirror關係

.步驟
. 登入 vSphere 客戶端。
. 若要編輯受保護叢集的屬性，您可以
+
.. 導覽至 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 選擇*新增關係*。
. 新增的關係作為*非同步*或*AutomatedFailOverDuplex*策略類型。
. 選擇*保護*。
+
您可以在「保護集群」視窗中看到變更。



vCenter 任務已創建，您可以在「最近任務」面板中追蹤進度。



== 刪除現有的SnapMirror關係

若要刪除非同步SnapMirror關係，應將輔助站點 SVM 或叢集新增為ONTAP tools for VMware vSphere上的儲存後端。您無法刪除所有SnapMirror關係。當您刪除關係時， ONTAP叢集上的對應關係也會被刪除。刪除 AutomatedFailOverDuplex SnapMirror關係時​​，目標上的資料儲存庫將取消映射，並且一致性群組、LUN、磁碟區和 igroup 將從目標ONTAP叢集中刪除。

刪除關係會觸發輔助網站上的重新掃描，以從主機中刪除未對應的 LUN 作為活動路徑。

.步驟
. 登入 vSphere 客戶端。
. 若要編輯受保護叢集的屬性，您可以
+
.. 導覽至 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 選擇SnapMirror設定下的省略號選單，然後選擇*刪除*。


vCenter 任務已創建，您可以在「最近任務」面板中追蹤進度。



== 修改現有的SnapMirror關係

若要修改非同步SnapMirror關係，應將輔助站點 SVM 或叢集新增為ONTAP tools for VMware vSphere上的儲存後端。如果是 AutomatedFailOverDuplex SnapMirror關係，則可以在統一配置的情況下修改主機接近度，在非統一配置的情況下修改主機存取。您不能互換非同步和 AutomatedFailOverDuplex 策略類型。您可以設定叢集上新發現的主機的接近度或存取權限。


NOTE: 您無法編輯現有的非同步SnapMirror關係。

.步驟
. 登入 vSphere 客戶端。
. 若要編輯受保護叢集的屬性，您可以
+
.. 導覽至 * NetApp ONTAP工具 * > * 保護 * > * 主機叢集關係 *，選擇叢集對應的省略號選單，然後選擇 * 編輯 * 或
.. 右鍵點選主機叢集並選擇 * NetApp ONTAP工具* > *保護叢集*。


. 如果選擇了 AutomatedFailOverDuplex 策略類型，請新增主機鄰近度或主機存取詳細資訊。
. 選擇*保護*按鈕。


vCenter 任務已創建，您可以在「最近任務」面板中追蹤進度。
